version: "3"
services:
  app:
    build:
      context: ./
    volumes:
      - ./src:/work
      - ./logs:/var/log/php
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=
