version: "3"
services:
  app:
    build:
      context: ./
    volumes:
      - ./src:/work
      - ./logs:/var/log/php
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=db
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_PORT=3306
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx/default.conf.tmp:/etc/nginx/conf.d/default.conf.tmp
    command: /bin/sh -c "envsubst '$$FASTCGI_PASS_HOST' < /etc/nginx/conf.d/default.conf.tmp > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - TZ=Asia/Tokyo
      - FASTCGI_PASS_HOST=app
    depends_on:
      - app
  db:
    build:
      context: ./mariadb/
    volumes:
      # - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
    ports:
      - 3306:3306
    # environment:
    #   - MYSQL_DATABASE=db
    #   - MYSQL_USER=user
    #   - MYSQL_PASSWORD=password
    #   - MYSQL_ROOT_PASSWORD=password

# volumes:
#   db-store: