version: "3"
services:
  app:
    build:
      context: ./
    volumes:
      - ./src:/work
      - ./logs:/var/log/php
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=lara-test
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_PORT=3307
  web:
    image: nginx:alpine
    ports:
      - 10080:80
    volumes:
      - ./src:/work
      - ./logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: /bin/sh -c "nginx -g 'daemon off;'"
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - app
  db:
    build:
      context: ./mariadb/
    volumes:
      # - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=lara-test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

# volumes:
#   db-store: